import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  darkMode: 'class',
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './app.vue',
  ],
  theme: {
    container: {
      center: true,
      padding: '1rem',
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Aura Gas Management design system — flat M3-style tokens, ported
        // verbatim (hex, not CSS vars: single fixed dark theme, no toggle)
        // so Stitch reference markup can be reused near-verbatim.
        surface: '#1d100c',
        'surface-dim': '#1d100c',
        'surface-bright': '#463630',
        'surface-container-lowest': '#170b07',
        'surface-container-low': '#261813',
        'surface-container': '#2a1c17',
        'surface-container-high': '#352721',
        'surface-container-highest': '#41312c',
        'surface-variant': '#41312c',
        'surface-tint': '#ffb59a',
        'on-surface': '#f7ddd5',
        'on-surface-variant': '#e2bfb3',
        'inverse-surface': '#f7ddd5',
        'inverse-on-surface': '#3c2d27',
        outline: '#a98a7f',
        'outline-variant': '#594139',
        'primary-container': '#ff6b2c',
        'on-primary-container': '#5c1c00',
        'on-primary': '#5b1b00',
        'primary-fixed': '#ffdbcf',
        'primary-fixed-dim': '#ffb59a',
        'on-primary-fixed': '#380d00',
        'on-primary-fixed-variant': '#802900',
        'inverse-primary': '#a83900',
        'secondary-container': '#3f465c',
        'on-secondary': '#283044',
        'on-secondary-container': '#adb4ce',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        tertiary: '#6cd2ff',
        'tertiary-container': '#00a6d6',
        'on-tertiary': '#003547',
        'on-tertiary-container': '#003648',
        'tertiary-fixed': '#bfe9ff',
        'tertiary-fixed-dim': '#6cd2ff',
        'on-tertiary-fixed': '#001f2a',
        'on-tertiary-fixed-variant': '#004d65',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'data-primary': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'data-secondary': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'data-tertiary': ['11px', { lineHeight: '14px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        'margin-mobile': '16px',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
