name = "gas-supplier-pwa"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gas-supplier-db"
database_id = "201ce0a7-2129-46e6-ab92-b9cc300cb786"
migrations_dir = "server/database/migrations"
